blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://terrain3d.readthedocs.io/
    about: Many questions and issues have already been answered, including status, tips, and troubleshooting.
  - name: Ask questions on Discord
    url: https://tokisan.com/discord
    about: Just have a question about features? Please use discord.
